name: Markdown Lint

on:
  push:
  pull_request:
    branches: [main]

jobs:
  markdownlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Run markdownlint-cli2
        uses: DavidAnson/markdownlint-cli2-action@v24.2.0
        with:
          globs: |
            **/*.md
